import { useState } from 'react'
import { Button, Input, Notice, Tabs } from '../../design'
import type { AuthIP, AuthMode, Proxy } from '../../api/keys'
import { useAddAuthIP, useDeleteAuthIP, useProxyAuthIPs, useSetProxyAuth } from '../../api/query'
import { AUTH_MODE_LABEL, usesIPList, usesUserPass } from './format'

export function deriveAuthMode(userpass: boolean, iplist: boolean): AuthMode | null {
  if (userpass && iplist) return 'both'
  if (userpass) return 'userpass'
  if (iplist) return 'iplist'
  return null
}

const CIDR_RE = /^(\d{1,3}(\.\d{1,3}){3}(\/\d{1,2})?|[0-9a-fA-F:]+(\/\d{1,3})?)$/

export function isPlausibleCidr(v: string): boolean {
  const s = v.trim()
  if (s === '' || !CIDR_RE.test(s)) return false
  if (s.includes('.')) {
    const [addr, bits] = s.split('/')
    const octets = (addr ?? '').split('.').map(Number)
    if (octets.some((n) => !Number.isInteger(n) || n < 0 || n > 255)) return false
    if (bits !== undefined && (Number(bits) < 0 || Number(bits) > 32)) return false
  }
  return true
}

function UserPassTab({ proxy }: { proxy: Proxy }) {
  const setAuth = useSetProxyAuth()
  const [enabled, setEnabled] = useState(usesUserPass(proxy))
  const [username, setUsername] = useState(proxy.username)
  const [password, setPassword] = useState('')
  const [rotate, setRotate] = useState(false)

  const iplist = usesIPList(proxy)
  const mode = deriveAuthMode(enabled, iplist)

  return (
    <form
      className="col"
      style={{ paddingTop: 12 }}
      onSubmit={(e) => {
        e.preventDefault()
        if (!mode) return
        setAuth.mutate({
          proxyId: proxy.id,
          body: {
            auth_mode: mode,
            username: enabled ? username : undefined,
            password: enabled && !rotate && password !== '' ? password : undefined,
            rotate_password: enabled && rotate ? true : undefined,
          },
        })
      }}
    >
      <label className="row">
        <input
          type="checkbox"
          checked={enabled}
          onChange={(e) => setEnabled(e.target.checked)}
        />
        <span>Require a username and password</span>
      </label>

      <Input
        label="Username"
        value={username}
        disabled={!enabled}
        onChange={(e) => setUsername(e.target.value)}
      />
      <Input
        label="Password"
        type="text"
        className="mono"
        placeholder={rotate ? 'generated by the server' : 'leave blank to keep the current one'}
        value={password}
        disabled={!enabled || rotate}
        onChange={(e) => setPassword(e.target.value)}
        hint="16 characters, letters and digits. Stored as 3proxy CL."
      />
      <label className="row">
        <input
          type="checkbox"
          checked={rotate}
          disabled={!enabled}
          onChange={(e) => setRotate(e.target.checked)}
        />
        <span>Generate a new password on save</span>
      </label>

      {!mode ? (
        <Notice tone="danger" title="At least one auth method must stay on">
          Turning both username/password and the IP whitelist off renders a 3proxy config that denies
          every connection.
        </Notice>
      ) : null}

      {setAuth.isError ? (
        <Notice tone="danger" title="Could not save auth">
          {setAuth.error.message}
        </Notice>
      ) : null}
      {setAuth.isSuccess ? (
        <Notice tone="ok" title="Auth change accepted">
          3proxy reloads on the backend; the listener stays bound.
        </Notice>
      ) : null}

      <div className="row">
        <Button type="submit" variant="primary" busy={setAuth.isPending} disabled={!mode}>
          Save credentials
        </Button>
        <span className="muted">Current mode: {AUTH_MODE_LABEL[proxy.auth_mode]}</span>
      </div>
    </form>
  )
}

function IPListTab({ proxy }: { proxy: Proxy }) {
  const list = useProxyAuthIPs(proxy.id)
  const add = useAddAuthIP()
  const del = useDeleteAuthIP()
  const setAuth = useSetProxyAuth()
  const [enabled, setEnabled] = useState(usesIPList(proxy))
  const [cidr, setCidr] = useState('')
  const [note, setNote] = useState('')

  const items: AuthIP[] = list.data?.items ?? []
  const userpass = usesUserPass(proxy)
  const mode = deriveAuthMode(userpass, enabled)
  const valid = isPlausibleCidr(cidr)

  return (
    <div className="col" style={{ paddingTop: 12 }}>
      <label className="row">
        <input type="checkbox" checked={enabled} onChange={(e) => setEnabled(e.target.checked)} />
        <span>Allow the networks below without a password</span>
      </label>

      {enabled && items.length === 0 ? (
        <Notice tone="warn" title="Empty whitelist denies everybody">
          An IP-list proxy with no entries renders as <code className="mono">deny *</code>. Add at
          least one network before saving.
        </Notice>
      ) : null}

      {!mode ? (
        <Notice tone="danger" title="At least one auth method must stay on">
          Turning both username/password and the IP whitelist off denies every connection.
        </Notice>
      ) : null}

      <ul className="list">
        {items.map((ip) => (
          <li key={ip.id} className="list-item" style={{ cursor: 'default' }}>
            <div className="row">
              <span className="mono grow">{ip.cidr}</span>
              {ip.note ? <span className="muted">{ip.note}</span> : null}
              <Button
                variant="danger"
                busy={del.isPending && del.variables?.cidr === ip.cidr}
                onClick={() => del.mutate({ proxyId: proxy.id, cidr: ip.cidr })}
                aria-label={`Remove ${ip.cidr}`}
              >
                Remove
              </Button>
            </div>
          </li>
        ))}
        {items.length === 0 && !list.isPending ? (
          <li className="muted">No networks whitelisted.</li>
        ) : null}
      </ul>

      <form
        className="row"
        onSubmit={(e) => {
          e.preventDefault()
          if (!valid) return
          add.mutate(
            { proxyId: proxy.id, cidr: cidr.trim(), note: note.trim() },
            { onSuccess: () => { setCidr(''); setNote('') } },
          )
        }}
      >
        <Input
          label="Source network (CIDR)"
          className="grow"
          value={cidr}
          placeholder="203.0.113.5/32"
          onChange={(e) => setCidr(e.target.value)}
          error={cidr !== '' && !valid ? 'Not a valid address or CIDR' : undefined}
        />
        <Input
          label="Note"
          className="grow"
          value={note}
          placeholder="customer office"
          onChange={(e) => setNote(e.target.value)}
        />
        <Button type="submit" busy={add.isPending} disabled={!valid}>
          Add network
        </Button>
      </form>

      {add.isError ? (
        <Notice tone="danger" title="Could not add the network">
          {add.error.message}
        </Notice>
      ) : null}

      <div className="row">
        <Button
          variant="primary"
          disabled={!mode || (enabled && items.length === 0)}
          busy={setAuth.isPending}
          onClick={() => {
            if (mode) setAuth.mutate({ proxyId: proxy.id, body: { auth_mode: mode } })
          }}
        >
          Save auth mode
        </Button>
        <span className="muted">Current mode: {AUTH_MODE_LABEL[proxy.auth_mode]}</span>
      </div>
    </div>
  )
}

export function AuthEditor({ proxy }: { proxy: Proxy }) {
  const [tab, setTab] = useState('userpass')
  return (
    <section className="card">
      <h3 className="card-title">Authentication</h3>
      <Tabs
        label="Authentication mode"
        active={tab}
        onChange={setTab}
        tabs={[
          { id: 'userpass', label: 'Username / password', panel: <UserPassTab proxy={proxy} /> },
          { id: 'iplist', label: 'IP whitelist', panel: <IPListTab proxy={proxy} /> },
        ]}
      />
    </section>
  )
}
